// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pdfvpdvwxcpcxahxzhxp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBkZnZwZHZ3eGNwY3hhaHh6aHhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MzI0MzcsImV4cCI6MjA2NDQwODQzN30.i-RoHWUbSys9887bUcGYVWo0cLPI1_F2HZiew52LIi4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);